[2024-03-22T14:05:50.564+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [queued]>
[2024-03-22T14:05:50.584+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [queued]>
[2024-03-22T14:05:50.585+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-03-22T14:05:50.619+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_check_result> on 2024-03-22 13:41:19.940286+00:00
[2024-03-22T14:05:50.631+0000] {standard_task_runner.py:60} INFO - Started process 487 to run task
[2024-03-22T14:05:50.645+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'get_check_result', 'manual__2024-03-22T13:41:19.940286+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmpxshvk3a6']
[2024-03-22T14:05:50.652+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask get_check_result
[2024-03-22T14:05:50.757+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [running]> on host ceb99a37e23c
[2024-03-22T14:05:50.952+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='get_check_result' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T13:41:19.940286+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-22T13:41:19.940286+00:00'
[2024-03-22T14:05:50.979+0000] {logging_mixin.py:188} INFO - BigQuery check failed!
[2024-03-22T14:05:50.980+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-22T14:05:51.002+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=source_to_gcs, task_id=get_check_result, execution_date=20240322T134119, start_date=20240322T140550, end_date=20240322T140551
[2024-03-22T14:05:51.068+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-22T14:05:51.128+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
