[2024-03-22T14:04:08.774+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [queued]>
[2024-03-22T14:04:08.787+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [queued]>
[2024-03-22T14:04:08.788+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-22T14:04:08.812+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_check_result> on 2024-03-22 13:41:19.940286+00:00
[2024-03-22T14:04:08.823+0000] {standard_task_runner.py:60} INFO - Started process 457 to run task
[2024-03-22T14:04:08.832+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'get_check_result', 'manual__2024-03-22T13:41:19.940286+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmpwiu9yotc']
[2024-03-22T14:04:08.837+0000] {standard_task_runner.py:88} INFO - Job 169: Subtask get_check_result
[2024-03-22T14:04:08.918+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.get_check_result manual__2024-03-22T13:41:19.940286+00:00 [running]> on host ceb99a37e23c
[2024-03-22T14:04:09.056+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='get_check_result' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T13:41:19.940286+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-22T13:41:19.940286+00:00'
[2024-03-22T14:04:09.078+0000] {logging_mixin.py:188} INFO - BigQuery check failed!
[2024-03-22T14:04:09.079+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-22T14:04:09.094+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=source_to_gcs, task_id=get_check_result, execution_date=20240322T134119, start_date=20240322T140408, end_date=20240322T140409
[2024-03-22T14:04:09.126+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-22T14:04:09.152+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
