[2024-03-18T01:45:50.679+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.confirm_file manual__2024-03-18T01:45:41.236416+00:00 [queued]>
[2024-03-18T01:45:50.710+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.confirm_file manual__2024-03-18T01:45:41.236416+00:00 [queued]>
[2024-03-18T01:45:50.711+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T01:45:50.746+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): confirm_file> on 2024-03-18 01:45:41.236416+00:00
[2024-03-18T01:45:50.760+0000] {standard_task_runner.py:60} INFO - Started process 12878 to run task
[2024-03-18T01:45:50.769+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'confirm_file', 'manual__2024-03-18T01:45:41.236416+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmpu3knfp4f']
[2024-03-18T01:45:50.778+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask confirm_file
[2024-03-18T01:45:50.884+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.confirm_file manual__2024-03-18T01:45:41.236416+00:00 [running]> on host 484fbc655ee6
[2024-03-18T01:45:51.083+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='confirm_file' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T01:45:41.236416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T01:45:41.236416+00:00'
[2024-03-18T01:45:51.087+0000] {python.py:202} INFO - Done. Returned value was: The File is present
[2024-03-18T01:45:51.169+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=source_to_gcs, task_id=confirm_file, execution_date=20240318T014541, start_date=20240318T014550, end_date=20240318T014551
[2024-03-18T01:45:51.235+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-18T01:45:51.292+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
